require("lib/landfill_absorbs_pollution")
require("lib/no_fast_inserters")
require("lib/no_signals")
require("lib/only_wood_for_train_fuel")
require("lib/unminable_demolisher_remains")
require("lib/unminable_spaceship")
